export {
	LesserHostSoulClient,
	LesserHostSoulClientError,
	createLesserHostSoulClient,
} from './client.js';
export {
	SoulBootstrapClient,
	SoulBootstrapClientError,
	createSoulBootstrapClient,
	normalizeSoulBootstrapError,
} from './bootstrap.js';
export type {
	ErrorEnvelope,
	FetchLike,
	LesserHostSoulClientConfig,
	ResolveEnsOptions,
	SoulAgentMintConversationsQuery,
	SoulAgentMintConversationsResponse,
	SoulAgentCommActivityItem,
	SoulAgentCommActivityQuery,
	SoulAgentCommActivityResponse,
	SoulAgentChannelsResponse,
	SoulAgentChannelPreferencesRequest,
	SoulAgentChannelPreferencesResponse,
	SoulAgentCommQueueItem,
	SoulAgentCommQueueQuery,
	SoulAgentCommQueueResponse,
	SoulAgentIdentity,
	SoulAnchorAssurance,
	SoulAnchorEvidence,
	SoulCommSendErrorEnvelope,
	SoulCommSendRequest,
	SoulCommSendResponse,
	SoulCommStatusErrorEnvelope,
	SoulCommStatusResponse,
	SoulMintConversation,
	SoulMintConversationCompleteRequest,
	SoulMintConversationFinalizeBeginRequest,
	SoulMintConversationFinalizePreflightResponse,
	SoulMintConversationFinalizeRequest,
	SoulMintConversationFinalizeResponse,
	SoulMintConversationSSEInput,
	SoulResolveResponse,
	SoulSearchQuery,
	SoulSearchResponse,
	SoulSearchResult,
} from './client.js';
export type {
	BeginSoulBootstrapInput,
	CompleteSoulBootstrapConversationInput,
	FinalizeSoulBootstrapInput,
	PrepareSoulBootstrapFinalizeInput,
	PrepareSoulBootstrapPrincipalDeclarationInput,
	SendSoulBootstrapConversationMessageInput,
	SoulBootstrapActionableError,
	SoulBootstrapClientConfig,
	SoulBootstrapCorrelationState,
	SoulBootstrapCurrentInput,
	SoulBootstrapErrorCategory,
	SoulBootstrapErrorState,
	SoulBootstrapGraphQLClient,
	SoulBootstrapGraphQLError,
	SoulBootstrapMutationPayload,
	SoulBootstrapMutationResult,
	SoulBootstrapPhase,
	SoulBootstrapPublicationEvidence,
	SoulBootstrapResult,
	SoulBootstrapSigningCheckpoint,
	SoulBootstrapState,
	SoulBootstrapSurface,
	VerifySoulBootstrapPrincipalDeclarationInput,
	VerifySoulBootstrapWalletInput,
} from './bootstrap.js';

export { resolveSoulAgentIdFromEnsTextRecord } from './ens.js';
export type { ResolveSoulAgentIdFromEnsTextRecordOptions } from './ens.js';
