export {
	LesserHostSoulClient,
	LesserHostSoulClientError,
	createLesserHostSoulClient,
} from './client.js';
export {
	SoulBootstrapClient,
	SoulBootstrapClientError,
	createSoulBootstrapClient,
	normalizeSoulBootstrapError,
} from './bootstrap.js';
export { HostedSoulBootstrapClient, createHostedSoulBootstrapClient } from './hostedBootstrap.js';
export {
	SoulBootstrapSigningPlanError,
	createSoulBootstrapSigningPlan,
	createSoulBootstrapSigningPlans,
} from './bootstrapSigningPlan.js';
export type {
	ErrorEnvelope,
	FetchLike,
	LesserHostSoulClientConfig,
	ResolveEnsOptions,
	SoulAgentMintConversationsQuery,
	SoulAgentMintConversationsResponse,
	SoulAgentCommActivityItem,
	SoulAgentCommActivityQuery,
	SoulAgentCommActivityResponse,
	SoulAgentChannelsResponse,
	SoulAgentChannelPreferencesRequest,
	SoulAgentChannelPreferencesResponse,
	SoulAgentCommQueueItem,
	SoulAgentCommQueueQuery,
	SoulAgentCommQueueResponse,
	SoulAgentIdentity,
	SoulAnchorAssurance,
	SoulAnchorEvidence,
	SoulCommSendErrorEnvelope,
	SoulCommSendRequest,
	SoulCommSendResponse,
	SoulCommStatusErrorEnvelope,
	SoulCommStatusResponse,
	SoulMintConversation,
	SoulMintConversationCompleteRequest,
	SoulMintConversationFinalizeBeginRequest,
	SoulMintConversationFinalizePreflightResponse,
	SoulMintConversationFinalizeRequest,
	SoulMintConversationFinalizeResponse,
	SoulMintConversationSSEInput,
	SoulResolveResponse,
	SoulSearchQuery,
	SoulSearchResponse,
	SoulSearchResult,
} from './client.js';
export type {
	BeginSoulBootstrapInput,
	CompleteSoulBootstrapConversationInput,
	FinalizeSoulBootstrapInput,
	PrepareSoulBootstrapFinalizeInput,
	PrepareSoulBootstrapPrincipalDeclarationInput,
	SendSoulBootstrapConversationMessageInput,
	SoulBootstrapActionableError,
	SoulBootstrapClientConfig,
	SoulBootstrapCorrelationState,
	SoulBootstrapCurrentInput,
	SoulBootstrapErrorCategory,
	SoulBootstrapErrorState,
	SoulBootstrapGraphQLClient,
	SoulBootstrapGraphQLClientProvider,
	SoulBootstrapGraphQLError,
	SoulBootstrapMutationPayload,
	SoulBootstrapMutationResult,
	SoulBootstrapPhase,
	SoulBootstrapPublicationEvidence,
	SoulBootstrapResult,
	SoulBootstrapSigningCheckpoint,
	SoulBootstrapState,
	SoulBootstrapSurface,
	VerifySoulBootstrapPrincipalDeclarationInput,
	VerifySoulBootstrapWalletInput,
} from './bootstrap.js';
export type {
	CompleteHostedSoulGenesisInput,
	HostedSoulBootstrapActionableError,
	HostedSoulBootstrapAnchorState,
	HostedSoulBootstrapAuthorityModel,
	HostedSoulBootstrapBoundSoulEvidence,
	HostedSoulBootstrapClientConfig,
	HostedSoulBootstrapCurrentInput,
	HostedSoulBootstrapHostRequestMetadata,
	HostedSoulBootstrapMode,
	HostedSoulBootstrapMutationPayload,
	HostedSoulBootstrapMutationResult,
	HostedSoulBootstrapNextAction,
	HostedSoulBootstrapPhase,
	HostedSoulBootstrapPublicationEvidence,
	HostedSoulBootstrapRecoveryAction,
	HostedSoulBootstrapRecoveryCategory,
	HostedSoulBootstrapResult,
	HostedSoulBootstrapState,
	HostedSoulBootstrapStateModel,
	HostedSoulBootstrapSurface,
	PublishHostedSoulInput,
	RestartSoulBootstrapInput,
	SendHostedSoulGenesisMessageInput,
	StartHostedSoulBootstrapInput,
} from './hostedBootstrap.js';
export type {
	SoulBootstrapFinalizeRequestTemplate,
	SoulBootstrapFinalizeSigningPlan,
	SoulBootstrapHexBytesSigningInstruction,
	SoulBootstrapHexString,
	SoulBootstrapMessageEncoding,
	SoulBootstrapPrincipalDeclarationSigningPlan,
	SoulBootstrapPrincipalDeclarationSubmitInput,
	SoulBootstrapSigningMethod,
	SoulBootstrapSigningPlan,
	SoulBootstrapSigningPlanErrorCode,
	SoulBootstrapSigningPlanErrorOptions,
	SoulBootstrapSigningPlanKind,
	SoulBootstrapSigningPlanSource,
	SoulBootstrapUtf8SigningInstruction,
	SoulBootstrapWalletChallengeSigningPlan,
	SoulBootstrapWalletSigningInstruction,
} from './bootstrapSigningPlan.js';

export { resolveSoulAgentIdFromEnsTextRecord } from './ens.js';
export type { ResolveSoulAgentIdFromEnsTextRecordOptions } from './ens.js';
