/**
 * @equaltoai/greater-components-adapters - Transport adapters and state management for Fediverse protocols
 */
import type { AiAnalysisQuery } from './graphql';
export type AIAnalysis = NonNullable<AiAnalysisQuery['aiAnalysis']>;
export { WebSocketClient } from './WebSocketClient';
export { SseClient } from './SseClient';
export { HttpPollingClient } from './HttpPollingClient';
export { TransportFallback } from './TransportFallback';
export { TransportManager } from './TransportManager';
export { WebSocketPool, getGlobalWebSocketPool, resetGlobalWebSocketPool } from './WebSocketPool';
export type { WebSocketPoolConfig, PooledWebSocket } from './WebSocketPool';
export {
	createGraphQLClient,
	getGraphQLClient,
	closeGraphQLClient,
	LesserGraphQLAdapter,
	createLesserGraphQLAdapter,
	typePolicies,
	cacheConfig,
	evictStaleCache,
	limitCacheSize,
	optimistic,
} from './graphql';
export type {
	GraphQLClientConfig,
	GraphQLClientInstance,
	LesserGraphQLAdapterConfig,
	TimelineVariables,
	CreateNoteVariables,
	CreateQuoteNoteMutationVariables,
	SearchVariables,
	Visibility,
	NotificationLevel,
	ObjectFieldsFragment,
	Actor,
	ViewerQuery,
	QuoteType,
	UploadMediaInput,
	MediaCategory,
	MediaType,
	UploadMediaMutationVariables,
	UploadMediaMutation,
	UploadMediaPayload,
} from './graphql';
export { createTimelineStore, createNotificationStore, createPresenceStore } from './stores';
export { AdminStreamingStore, createAdminStreamingStore } from './stores/adminStreamingStore';
export type {
	MetricsUpdate,
	ModerationAlert,
	CostAlert,
	BudgetAlert,
	FederationHealthUpdate,
	ModerationQueueItem,
	ThreatIntelligence,
	PerformanceAlert,
	InfrastructureEvent,
	AdminStreamingStoreState,
	AdminStreamingStoreConfig,
} from './stores/adminStreamingStore';
export {
	unifiedStatusToTimelineItem,
	unifiedStatusesToTimelineItems,
} from './stores/unifiedToTimeline';
export {
	unifiedNotificationToStoreNotification,
	unifiedNotificationsToStoreNotifications,
} from './stores/unifiedToNotification';
export {
	StreamingOperationsManager,
	TimelineStreamingHandler,
	NotificationStreamingHandler,
	AccountStreamingHandler,
	DeleteStreamingHandler,
	EditStreamingHandler,
	StreamingStateManager,
} from './streaming/operations';
export type {
	StreamingOperation,
	StreamingOperationHandler,
	StreamingState,
	StreamingConfig,
} from './streaming/operations';
export {
	mapMastodonAccount,
	mapMastodonStatus,
	mapMastodonNotification,
	mapMastodonStreamingEvent,
	batchMapMastodonAccounts,
	batchMapMastodonStatuses,
	batchMapMastodonNotifications,
	mapLesserAccount,
	mapLesserPost,
	mapLesserNotification,
	mapLesserStreamingUpdate,
	handleLesserGraphQLResponse,
	mapLesserTimelineConnection,
	batchMapLesserAccounts,
	batchMapLesserPosts,
	batchMapLesserNotifications,
	mapLesserObject,
	convertGraphQLObjectToLesser,
	MapperUtils,
} from './mappers';
export type {
	BaseTransportConfig,
	TransportAdapter,
	TransportFallbackConfig,
	TransportType,
	TransportManagerConfig,
	TransportManagerState,
	TransportSwitchEvent,
	TransportEventMap,
	TransportEventName,
	WebSocketClientConfig,
	WebSocketClientState,
	WebSocketMessage,
	WebSocketEvent,
	WebSocketEventType,
	WebSocketEventHandler,
	SseClientConfig,
	SseClientState,
	SseMessage,
	HttpPollingClientConfig,
	HttpPollingClientState,
	HttpPollingMessage,
	HeartbeatMessage,
	LatencySample,
} from './types';
export type {
	TimelineStore,
	NotificationStore,
	PresenceStore,
	BaseStore,
	StoreFactory,
	TimelineItem,
	TimelineState,
	TimelineConfig,
	Notification,
	NotificationState,
	NotificationConfig,
	NotificationFilter,
	NotificationAction,
	LesserTimelineMetadata,
	LesserNotificationMetadata,
	UserPresence,
	SessionInfo,
	PresenceState,
	PresenceConfig,
	StreamingEdit,
	JsonPatch,
} from './stores/types';
export type {
	UnifiedAccount,
	UnifiedStatus,
	UnifiedNotification,
	SourceMetadata,
	MediaAttachment,
	MediaMeta,
	Mention,
	Tag,
	TagHistory,
	CustomEmoji,
	Poll,
	PollOption,
	AccountField,
	AccountRelationship,
	AdminReport,
	StreamingUpdate,
	StreamingDelete,
	StreamingEdit as UnifiedStreamingEdit,
	MappingError,
	MapperResult,
	BatchMapperResult,
	ValidationRule,
	FieldValidator,
} from './mappers';
export type {
	MastodonAccount,
	MastodonField,
	MastodonEmoji,
	MastodonRelationship,
	MastodonStatus,
	MastodonMediaAttachment,
	MastodonMediaMeta,
	MastodonMention,
	MastodonTag,
	MastodonTagHistory,
	MastodonPreviewCard,
	MastodonPoll,
	MastodonPollOption,
	MastodonNotification,
	MastodonReport,
	MastodonStreamingEvent,
	MastodonInstance,
	MastodonRule,
	MastodonError,
	MastodonPaginationParams,
	MastodonPaginatedResponse,
} from './mappers';
export type {
	LesserGraphQLResponse,
	LesserGraphQLError,
	LesserAccountFragment,
	LesserProfileField,
	LesserEmojiFragment,
	LesserRelationshipFragment,
	LesserPostFragment,
	LesserInteractionCounts,
	LesserUserInteractions,
	LesserMediaFragment,
	LesserMediaMetadata,
	LesserMentionFragment,
	LesserHashtagFragment,
	LesserTrendingData,
	LesserPollFragment,
	LesserPollOption,
	LesserNotificationFragment,
	LesserAdminReportFragment,
	LesserTimelineConnection,
	LesserTimelineEdge,
	LesserPageInfo,
	LesserStreamingUpdate,
	LesserStreamingData,
	LesserPostStreamingData,
	LesserNotificationStreamingData,
	LesserAccountStreamingData,
	LesserDeleteStreamingData,
	LesserGetTimelineQuery,
	LesserGetTimelineVariables,
	LesserGetNotificationsQuery,
	LesserGetNotificationsVariables,
	LesserCreatePostMutation,
	LesserCreatePostVariables,
	LesserInstanceInfo,
	LesserValidationError,
	LesserMutationError,
	LesserTimelineSubscription,
	LesserNotificationSubscription,
} from './mappers';
export type {
	LesserReputationFragment,
	LesserVouchFragment,
	LesserCommunityNoteFragment,
	LesserQuoteContextFragment,
	LesserAIAnalysisFragment,
} from './mappers/lesser/types.js';
//# sourceMappingURL=index.d.ts.map
